#pragma once

const int QUERYOSIDERRNUM = 1;

const int CREATESGERRNUM = 2;
const int CONFIGSGERRNUM = 3;
const int DELETESGERRNUM = 4;

const int DESCRIBEREGIONSERRNUM = 5;
const int DESCRIBEAZSERRNUM = 6;

const int CREATEINSTANCESERRNUM = 7;
const int CREATEINSTANCESWRONGAMOUNTERRNUM = 8;

const int UPDATEINSTANCESERRNUM = 9;
const int UPDATEINSTANCESWRONGAMOUNTERRNUM = 10;

const int TERMINATEINSTANCESERRNUM = 11;

const int LISTTABLESERRNUM = 12;
const int CREATETABLEERRNUM = 13;
const int DESCRIBETABLEERRNUM = 14;
