#pragma once

const int QUERYOSIDERRNUM = 1;

const int CREATESGERRNUM = 2;
const int CONFIGSGERRNUM = 3;
const int DELETESGERRNUM = 4;

const int DESCRIBEREGIONSERRNUM = 5;
const int DESCRIBEAZSERRNUM = 6;

const int CREATEINSTANCESERRNUM = 7;
const int CREATEINSTANCESWRONGAMOUNTERRNUM = 8;
