/**
 * EC2 network latency project
 *
 * File: errorCode.h
 *
 * Author: Jung Chak
 *
 * Error codes
 */

#pragma once

const int QUERYOSIDERRNUM = 1;

const int CREATESGERRNUM = 2;
const int CONFIGSGERRNUM = 3;
const int DELETESGERRNUM = 4;

const int DESCRIBEREGIONSERRNUM = 5;
const int DESCRIBEAZSERRNUM = 6;

const int CREATEINSTANCESERRNUM = 7;
const int CREATEINSTANCESWRONGAMOUNTERRNUM = 8;

const int UPDATEINSTANCESERRNUM = 9;
const int UPDATEINSTANCESWRONGAMOUNTERRNUM = 10;

const int TERMINATEINSTANCESERRNUM = 11;

const int LISTTABLESERRNUM = 12;
const int CREATETABLEERRNUM = 13;
const int DESCRIBETABLEERRNUM = 14;
const int QUERYTABLEERRNUM = 15;
const int PUTDBENTRYERRNUM = 16;
const int PUTSTATENTRYERRNUM = 17;

const int RESTOULLERRNUM = 18;
const int HDSTOULLERRNUM = 19;
const int RTTTOULLERRNUM = 20;

const int MINIONCONNECTIONERRNUM = 21;
const int MINIONSENDERRNUM = 22;
const int MINIONRECVERRNUM = 23;

const int MINIONNOTPROCEEDERRNUM = 24;
const int MINIONROLEERRNUM = 25;
const int MINIONNOTBYEERRNUM = 26;
